workaround for compilation error about missing isspace
top/driver.c: In function 'helpfunc':
top/driver.c:1333:24: error: implicit declaration of function 'isspace' [-Wimplicit-function-declaration]
 1333 |                 while (isspace((int)s[j])) j++;         //skip white space