workaround for compilation error about missing isdigit
top/cmdParser/cmdOptions.c: In function 'enforce_numeric':
top/cmdParser/cmdOptions.c:274:14: error: implicit declaration of function 'isdigit' [-Wimplicit-function-declaration]
  274 |         if (!isdigit((int)arg[i]))
      |              ^~~~~~~