workaround for compilation error about missing pthread
factor/qs/msieve/lanczos_matmul0.c: In function 'yafu_mul_packed':
factor/qs/msieve/lanczos_matmul0.c:131:25: error: implicit declaration of function 'pthread_cond_signal' [-Wimplicit-function-declaration]
  131 |                         pthread_cond_signal(&t->run_cond);
      |                         ^~~~~~~~~~~~~~~~~~~